# Regenerate ANSI sprites from PNG sources via chafa.
# Run after updating any source PNG, or after a chafa version upgrade.

$ErrorActionPreference = 'Stop'
$sourceDir = "$PSScriptRoot/sources"
$outputDir = $PSScriptRoot

if (-not (Get-Command chafa -ErrorAction SilentlyContinue)) {
    Write-Host "chafa not installed. Install it first:" -ForegroundColor Red
    Write-Host "  scoop install chafa" -ForegroundColor Yellow
    Write-Host "  -OR- choco install chafa" -ForegroundColor Yellow
    Write-Host "  -OR- https://hpjansson.org/chafa/" -ForegroundColor Yellow
    exit 1
}

$animals = @('raccoon', 'hedgehog', 'octopus', 'owl', 'fox', 'turtle')
$generated = 0
$skipped = 0

foreach ($name in $animals) {
    $src = Join-Path $sourceDir "$name.png"
    $dst = Join-Path $outputDir "$name.ansi"
    if (-not (Test-Path $src)) {
        Write-Host "Missing source: sources/$name.png — skipping" -ForegroundColor Yellow
        $skipped++
        continue
    }
    Write-Host "Converting $name..." -ForegroundColor Cyan
    $header = @"
# Stardew-style $name sprite — tier-3 half-block ANSI.
# Regenerated by animals/regen.ps1 from sources/$name.png
# Generated: $(Get-Date -Format 'yyyy-MM-dd')

"@
    $art = & chafa --size 30x20 --symbols half --colors 256 --animate=off --polite=on $src
    Set-Content -Path $dst -Value ($header + ($art -join "`n")) -Encoding UTF8
    $generated++
}

Write-Host ""
Write-Host "Generated: $generated   Skipped: $skipped" -ForegroundColor Green
if ($skipped -gt 0) {
    Write-Host "Add missing PNGs to animals/sources/ and rerun." -ForegroundColor Yellow
}
